Now returning an error package when receiving the wrong block number
connorkuehl/tftp pull request #45
Opened 2020-10-05 16:17 UTC by 1c3t3a

Closes #35. The connection::put Method now sends an error package before ending the communication in case the current_block count is not plausible.

2020-10-05 17:12 UTC, 1c3t3a commented
I dont't really get how he's not finding [std::io::Error](https://doc.rust-lang.org/std/io/struct.Error.html) in the [error log](https://travis-ci.com/github/connorkuehl/tftp/jobs/395267498).

2020-10-05 21:28 UTC, connorkuehl commented
@1c3t3a it's because your development branch is out-of-date with my branch and that import statement might have disappeared since then. No worries! This is easily fixed by rebasing on top of my branch.

When you're on your local branch:

```console
$ git fetch https://github.com/connorkuehl/tftp main
$ git rebase FETCH_HEAD
```

There might be some merge conflicts that need to be resolved.

2020-10-06 05:18 UTC, 1c3t3a commented
> @1c3t3a it's because your development branch is out-of-date with my branch and that import statement might have disappeared since then. No worries! This is easily fixed by rebasing on top of my branch.
> 
> When you're on your local branch:
> 
> ```
> $ git fetch https://github.com/connorkuehl/tftp main
> $ git rebase FETCH_HEAD
> ```
> 
> There might be some merge conflicts that need to be resolved.

Ah I see! I rebased and added the import again, now it should work fine!

2020-10-06 22:08 UTC, connorkuehl requested changes

2020-10-06 22:08 UTC, connorkuehl commented on src/connection.rs
> +                );
```suggestion
                let error = Packet::error(
                    Code::IllegalOperation,
                    format!("expected ACK for {} but got ACK for {}", current_block, ack.body.block),
                );
```

Awesome! Just a couple of tweaks. I don't think we have to turbofish `Packet::<Error>::error`, I think Rust knows which `Packet<T>` we mean when we use `Packet::error`.

I tweaked the error message to include more info.

I haven't tried compiling these suggestions so maybe a bit of massaging is necessary.

2020-10-07 22:20 UTC, connorkuehl approved these changes
Thank you so much! :slightly_smiling_face:

2020-10-07 22:20 UTC, merged