Add Server.serve() unit test
connorkuehl/tftp pull request #52
Opened 2020-10-08 01:28 UTC by noblehelm

Add a specific unit test for Server.serve() function, for when the
Server receives a request that is not a _read_ or _write_ request, which
implies no use of OPCODES 1 or 2, which then should return an error.

2020-10-08 01:28 UTC, noblehelm commented
Issue #29

2020-10-08 12:22 UTC, noblehelm commented
Another test is failing on the windows platform, test_get() in get.rs, due to a permission denied. What can I do to fix it? Or at least run the checks again to see if it fails one more time?

2020-10-08 15:15 UTC, noblehelm commented
I did a rebase with the recent changes from upstream and somehow, something fixed it. I hope this resolves everything.

2020-10-09 22:19 UTC, connorkuehl requested changes
Overall, this looks really good! I just requested a couple of tweaks to take advantage of helpful bits of code that have been merged in this repo. I'm mainly trying to reduce the number of hard-coded port numbers in the tests because as they grow it'll get harder to keep track of which ports are used by which tests.

2020-10-09 22:19 UTC, connorkuehl commented on tests/server.rs
> +    let server = Server::new(&server_addr, serve_dir.path()).unwrap();
```suggestion
    let serve_addr = "127.0.0.1";
    let (port, server) = Server::random_port(serve_addr, serve_dir.path()).unwrap();
```

2020-10-21 00:28 UTC, connorkuehl approved these changes
Looks great, thank you 😁

2020-10-21 00:29 UTC, connorkuehl requested changes
Oops, sorry. I didn't see that Travis CI was failing while I reviewed this on mobile. Could you fix the compiler errors?

2020-10-21 21:57 UTC, noblehelm commented
I had to change back into making a bad packet by hand, because I could not use the .into_bytes() function, from the private trait IntoBytes, considering this is an 'integration' test. Importing it would end up giving errors. So I had to fallback to that format. All of the other changes you requested were made. Thanks in advance.

2020-10-21 22:41 UTC, connorkuehl approved these changes
Thanks!

2020-10-21 22:41 UTC, merged