Resend last Ack in case it gets lost
connorkuehl/tftp pull request #59
Opened 2020-10-22 08:37 UTC by 1c3t3a

Closes #56. Sets a timeout for "acking" the last package to three seconds. If the server sends the last packet again, the last Ack gets sent again. Due to platform specific behavior, the socket timeout expects either an `ErrorKind::WouldBlock` (Unix) or an `ErrorKind::TimedOut` (Windows) Error.

2020-10-22 09:52 UTC, 1c3t3a commented
Should I squash my commits?

2020-10-23 23:41 UTC, connorkuehl commented
> Should I squash my commits?

Yes, please rebase and squash your commits so that each commit is a single logical change 🙂

2020-10-26 06:07 UTC, 1c3t3a commented
Done!

2020-10-30 14:52 UTC, 1c3t3a commented
Hey! I don't want to stress you but as hacktoberfest ends in two days is it possible for you to review this PR? Thanks a lot!

2020-10-30 15:01 UTC, connorkuehl commented
Sure! Please fix the merge conflicts and I'll review it. It looks like these showed up because you merged my branch into yours instead of rebasing on top of my branch.

2020-10-31 03:18 UTC, 1c3t3a commented
> Sure! Please fix the merge conflicts and I'll review it. It looks like these showed up because you merged my branch into yours instead of rebasing on top of my branch.

Alright, done!

2020-10-31 12:56 UTC, connorkuehl commented
The merge conflicts are still unresolved. If you look at the "Commits" tab of your PR you can see merge commits causing conflicts.

2020-10-31 14:12 UTC, 1c3t3a commented
> The merge conflicts are still unresolved. If you look at the "Commits" tab of your PR you can see merge commits causing conflicts. These will need to be removed so it's _only_ your commits without any merge commits.
Uff, came a long way, sorry!

2020-10-31 15:29 UTC, connorkuehl requested changes

2020-10-31 15:29 UTC, connorkuehl commented on src/connection.rs
> +                    self.socket.set_read_timeout(Some(Duration::new(3, 0)))?;
Setting the read timeout is persistent, so this can be done just once before entering the loop

2020-10-31 16:40 UTC, connorkuehl approved these changes
Thank you! 🙂

2020-10-31 16:40 UTC, merged